timeout = 30
retry_wait_time = 5
max_retries = 6
max_concurrency = 4

# Check link anchors
include_fragments = true

exclude = [
  '^https://developers.redhat.com/download-manager/file/jboss-eap-.*.zip',
  '^http://localhost.*',
  '^https://central.sonatype.com/service/rest/repository/browse/maven-snapshots/com/splunk/',
  '^https://quickdraw.splunk.com/redirect/.*'
]
